name: IntelliJ Reformat Code

on:
  push:
    branches: [ test ]

jobs:
  reformat:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: ./
